version: '2' 
services:
  web:
    build: 
      context: .
      args:
        DEV: 'true'
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
  cloud9:
    image: kdelfour/cloud9-docker
    volumes:
      - ./:/workspace
    ports:
      - 8081:80
   

